### ISSUE TITLE
Add graph charts

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Python_Toolkit#21]
From @tg359 library of fancy graphs

**Comment by tg359** [comment]
Adding an example script here to test on in case it's useful 😄

[bhom_pythontoolkit.zip](https://github.com/BHoM/Python_Toolkit/files/4877987/bhom_pythontoolkit.zip)

**Comment by tg359** [comment]
Here are the versions I'm using my side, if we need to specify a fixed version (and that fixes the bugs 🤞).

[requirements.txt](https://github.com/BHoM/Python_Toolkit/files/4883593/requirements.txt)

The packages being used in the plotting methods are:
- pandas
- PsychroLib
- matplotlib
- numpy
- windrose

**Comment by epignatelli** [comment]
Installing windrose from git allows for compatibility with matplotlib 3.2.0
`pip install git+https://github.com/python-windrose/windrose`

**Comment by FraserGreenroyd** [comment]
This issue is now covered by https://github.com/BHoM/MachineLearning_Toolkit/issues/27 so am closing this issue for clarity.
