### ISSUE TITLE
Prepare the toolkit to be in the installer

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Python_Toolkit#5]
#### Broken rules:

Broken rules are uncertain and the goal of the issue is right to explore what compliance problems we have here.

#### Additional tasks
- Include `matplotlib` into the bacis packages

**Comment by FraserGreenroyd** [comment]
I've made a start on this in #18 PR for reference.

The following actions need to be completed to ensure this toolkit can be included in the installers:

 - Update everything to use `ProgramData` and not `AppData` - references and also installation folders
 - Remove the need to `PostBuild` to be run separately, wrap the actions within a Compute method so this can be run by users on the UIs
 - A general review of installer inclusion guidelines
