### ISSUE TITLE
Installing a C# kernel in Jupyter?

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Python_Toolkit#8]
JupyterLab is a widely used interface to a series of tools. it is used a lot with Python, and support multiple kernels, such as C++, C#, Julia, R.
https://towardsdatascience.com/jupyter-lab-evolution-of-the-jupyter-notebook-5297cacde6b

I think it is worth exploring the use of JupyterHub with a C# kernel. it can be useful to swiftly test things and to push and pull data without the need of opening Grasshopper - just by writing some code.

**Comment by rboulton-BH** [comment]
Following discussion with @FraserGreenroyd - there isn't sufficient capacity to support JupyterLab for C#. We already have other methods of achieving the same outcome through Visual Studio console apps.
