### ISSUE TITLE
InstallPython fails when Python already exists and `force`=true

### ISSUE THREAD

**Issue by jamesramsden-bh** [BHoM/Python_Toolkit#81]
#### How to replicate:
Have the following file already exist: 'C:\\ProgramData\\BHoM\\Extensions\\Python\\python.exe'. Then, run InstallPython with `force`=true. 

Fails on line 61, "The file 'C:\\ProgramData\\BHoM\\Extensions\\Python\\python.exe' already exists."

#### Expected behaviour:
Python successfully reinstalled, success == true.

**Comment by tg359** [comment]
I need to take a look at the wider installation logic for Python Environments here, there's a lot of checking to make sure environments do/don't exist and whether to skip parts of the code to speed up the process. Could be made a lot faster ~probably~ definitely.
